import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import worker,{summarise,validate} from '../worker/index.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const headers={'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25'};
const rpc=async(method,params={},id=1,extra={})=>worker.fetch(new Request('https://demo.test/mcp',{method:'POST',headers:{...headers,...extra},body:JSON.stringify({jsonrpc:'2.0',id,method,params})}));
const args={latitude:49,longitude:32,start_date:'2024-09-01',end_date:'2024-09-03'};
assert.throws(()=>validate({...args,start_date:'2024-02-30'}));
assert.throws(()=>validate({...args,latitude:91}));
assert.throws(()=>validate({...args,baseline_years:[2021,2021,2023]},true));
assert.throws(()=>validate({...args,baseline_years:[2021,2022,2024]},true));
assert.throws(()=>validate({...args,end_date:'2025-01-01'}));
const init=await(await rpc('initialize',{protocolVersion:'2025-11-25',clientInfo:{name:'test',version:'1'},capabilities:{}})).json();
assert.equal(init.result.protocolVersion,'2025-11-25');
assert.equal((await(await rpc('tools/list')).json()).result.tools.length,2);
assert.equal((await rpc('ping',{},1,{Origin:'https://evil.test'})).status,403);
assert.equal((await rpc('ping',{},1,{'MCP-Protocol-Version':'2099-01-01'})).status,400);
assert.equal((await rpc('ping',{},1,{Accept:'application/json'})).status,406);
assert.equal((await(await rpc('unknown')).json()).error.code,-32601);
assert.equal((await(await rpc('tools/call',{name:'missing'})).json()).error.code,-32602);
assert.equal((await worker.fetch(new Request('https://demo.test/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})}))).status,202);
assert.equal((await worker.fetch(new Request('https://demo.test/mcp'))).status,405);
assert.equal((await(await rpc('resources/read',{uri:'agropredict://demo-guide'})).json()).result.contents.length,1);
const fixture={header:{fill_value:-999,time_standard:'UTC',sources:['TEST FIXTURE'],api:{version:'test'}},parameters:{T2M:{units:'C'},PRECTOTCORR:{units:'mm/day'},RH2M:{units:'%'}},properties:{parameter:{T2M:{20240901:10,20240902:20,20240903:-999},PRECTOTCORR:{20240901:0,20240902:2,20240903:4},RH2M:{20240901:40,20240902:50,20240903:60}}}};
const summary=summarise(fixture,args);
assert.equal(summary.parameters.T2M.valid_days,2);
assert.equal(summary.parameters.T2M.mean,15);
assert.equal(summary.daily.T2M['20240903'],null);
assert.equal(summary.parameters.PRECTOTCORR.observed_total_mm,6);
assert.equal(summary.parameters.PRECTOTCORR.total_complete,true);
// Exercise entire MCP tool path with controlled upstream, not published as real data.
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url)=>{
 const y=Number(new URL(url).searchParams.get('start').slice(0,4));
 const f=structuredClone(fixture);
 f.properties.parameter={};
 for(const p of ['T2M','PRECTOTCORR','RH2M'])f.properties.parameter[p]=Object.fromEntries([1,2,3].map(d=>[`${y}090${d}`,p==='T2M'?(y===2024?20:10):p==='RH2M'?(y===2024?60:50):0]));
 if(y===2022)f.properties.parameter.RH2M[`${y}0902`]=-999;
 return new Response(JSON.stringify(f));
};
const out=(await(await rpc('tools/call',{name:'compare_climate_history',arguments:{...args,baseline_years:[2021,2022,2023]}})).json()).result;
assert.equal(out.isError,false);
assert.equal(out.structuredContent.comparisons.T2M.absolute_delta,10);
assert.equal(out.structuredContent.comparisons.PRECTOTCORR.relative_delta_percent,null);
assert.equal(out.structuredContent.comparisons.RH2M.status,'unavailable');
assert.equal(out.structuredContent.status,'partial');
assert.equal(out.structuredContent.provenance.length,4);
assert.equal(out.structuredContent.provenance[0].response_sha256.length,64);
globalThis.fetch=originalFetch;
console.log('PASS: MCP lifecycle, discovery, resources, validation, source provenance, missing coverage and zero baseline.');
